# Generated by Django 6.0.3 on 2026-04-29 15:09

import ecommerce.product.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productline',
            name='order',
            field=ecommerce.product.fields.OrderField(blank=True, null=True),
        ),
    ]
